import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Components/Day2Components/ThemeContext";
import { LanguageProvider } from "@/Components/Day2Components/LanguageContext";
import { ShoppingCartProvider } from "@/Components/Day2Components/ShoppingCartContext";
import { ParentProvider } from "@/Components/Day3Components/ParentContext";
import { LightLoginProvider } from "@/Components/Day3Components/LightLoginContext";
import {  ValidationProvider } from "@/Components/Day3Components/ValidationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <LanguageProvider>
            <ShoppingCartProvider>

              <LightLoginProvider>

                <ValidationProvider>
                   {children}
                </ValidationProvider>
                 
               </LightLoginProvider>
          
              </ShoppingCartProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
  
}
